version: '3.10'
services:
  app:
    build: .
    command: >
      sh -c "cd app && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    expose:
      - 8000